export interface VoiceData {
  voice: string;
  card: string;
  part: number; // 1: who, 2: where, 3: why, 4: what
}

export const CHARACTERS = {
  ta: { 
    id: 'ta', 
    name: '富良野のお兄さん', 
    folder: 'takahiro_kurono', 
    color: '#3b82f6', 
    image: 'assets/img/ta_265.png' 
  },
  ka: { 
    id: 'ka', 
    name: '浦和のお姉さん', 
    folder: 'kasukabe', 
    color: '#ec4899', 
    image: 'assets/img/ka_265.png' 
  },
  ne: { 
    id: 'ne', 
    name: 'アキバのメイドさん', 
    folder: 'nekotuka', 
    color: '#10b981', 
    image: 'assets/img/ne_265.png' 
  },
  so: {
    id: 'so',
    name: '北谷町の漁師',
    folder: 'kigasima',
    color: '#f97316',
    image: 'assets/img/so_265.png'
  },
} as const;

export type CharKey = keyof typeof CHARACTERS;

export const VOICE_DB: VoiceData[] = [
  { voice: "ta_wha_1", card: "プロテインを飲み干した", part: 4},
  { voice: "ta_wha_2", card: "反省文を書いた", part: 4},
  { voice: "ta_wha_3", card: "熱々のラーメンをすすった", part: 4},
  { voice: "ta_wha_4", card: "咀嚼音のASMRを聴いた", part: 4},
  { voice: "ta_wha_5", card: "プロポーズに大成功した", part: 4},
  { voice: "ta_wha_6", card: "座禅を組んだ", part: 4},
  { voice: "ta_whe_1", card: "予約の取れない寿司屋で", part: 2},
  { voice: "ta_whe_2", card: "秘密の地下組織で", part: 2},
  { voice: "ta_whe_3", card: "サウナの最上段で", part: 2},
  { voice: "ta_whe_4", card: "実家の四畳半で", part: 2},
  { voice: "ta_whe_5", card: "回転寿司のレーン上で", part: 2},
  { voice: "ta_whe_6", card: "図書館の真ん中で", part: 2},
  { voice: "ta_who_1", card: "エジプトのミイラが", part: 1},
  { voice: "ta_who_2", card: "ドラえもんが", part: 1},
  { voice: "ta_who_3", card: "アラブの石油王が", part: 1},
  { voice: "ta_who_4", card: "地獄のエンマ大王が", part: 1},
  { voice: "ta_who_5", card: "シュワルツェネッガーが", part: 1},
  { voice: "ta_who_6", card: "眉毛のないヤンキーが", part: 1},
  { voice: "ka_wha_1", card: "百円玉を拾った", part: 4},
  { voice: "ka_wha_2", card: "激しくサンバを踊った", part: 4},
  { voice: "ka_wha_3", card: "ブロッコリーをむさぼり食った", part: 4},
  { voice: "ka_wha_4", card: "宇宙人とチェスをした", part: 4},
  { voice: "ka_wha_5", card: "涙をながしながら謝罪した", part: 4},
  { voice: "ka_wha_6", card: "薄い本を破り捨てた", part: 4},
  { voice: "ka_whe_1", card: "マクドナルドで", part: 2},
  { voice: "ka_whe_2", card: "コインランドリーで", part: 2},
  { voice: "ka_whe_3", card: "宇宙の果てで", part: 2},
  { voice: "ka_whe_4", card: "富士山の山頂で", part: 2},
  { voice: "ka_whe_5", card: "無人島の砂浜で", part: 2},
  { voice: "ka_whe_6", card: "部室のロッカーの中で", part: 2},
  { voice: "ka_who_1", card: "織田信長が", part: 1},
  { voice: "ka_who_2", card: "トランプ大統領が", part: 1},
  { voice: "ka_who_3", card: "となりのおじいさんが", part: 1},
  { voice: "ka_who_4", card: "謎の覆面レスラーが", part: 1},
  { voice: "ka_who_5", card: "担任の先生が", part: 1},
  { voice: "ka_who_6", card: "ピカピカの一年生が", part: 1},
  { voice: "ne_wha_1", card: "写生した", part: 4},
  { voice: "ne_wha_2", card: "般若心経をとなえ続けた", part: 4},
  { voice: "ne_wha_3", card: "ポイントカードを紛失してキレた", part: 4},
  { voice: "ne_wha_4", card: "みかんの皮をむいた", part: 4},
  { voice: "ne_wha_5", card: "変顔の自撮りを投稿した", part: 4},
  { voice: "ne_wha_6", card: "前髪のセットに命をかけた", part: 4},
  { voice: "ne_whe_1", card: "満員のエレベーターの中で", part: 2},
  { voice: "ne_whe_2", card: "渋谷のスクランブル交差点で", part: 2},
  { voice: "ne_whe_3", card: "ドラッグストアのレジ前で", part: 2},
  { voice: "ne_whe_4", card: "おばあちゃんの家のコタツで", part: 2},
  { voice: "ne_whe_5", card: "上場企業の株主総会で", part: 2},
  { voice: "ne_whe_6", card: "真夜中の音楽室で", part: 2},
  { voice: "ne_who_1", card: "宇宙人が", part: 1},
  { voice: "ne_who_2", card: "二足歩行のロボットが", part: 1},
  { voice: "ne_who_3", card: "伝説の勇者が", part: 1},
  { voice: "ne_who_4", card: "怪盗ルパンの孫が", part: 1},
  { voice: "ne_who_5", card: "セクシーなお姉ちゃんが", part: 1},
  { voice: "ne_who_6", card: "AIの搭載された電子レンジが", part: 1},
  { voice: "ka_who_7", card: "総理大臣が", part: 1},
  { voice: "ka_who_8", card: "敏腕社長が", part: 1},
  { voice: "ka_who_9", card: "悪魔が", part: 1},
  { voice: "ka_who_10", card: "ウーバー配達員が", part: 1},
  { voice: "ka_who_11", card: "異世界に転生した男が", part: 1},
  { voice: "ka_who_12", card: "迷子のAIロボットが", part: 1},
  { voice: "ka_who_13", card: "頑固な職人が", part: 1},
  { voice: "ta_who_7", card: "お忍びの王様が", part: 1},
  { voice: "ta_who_8", card: "非番の警察官が", part: 1},
  { voice: "ta_who_9", card: "大富豪の飼い猫が", part: 1},
  { voice: "ta_who_10", card: "メイド長が", part: 1},
  { voice: "ta_who_11", card: "自称・天才科学者が", part: 1},
  { voice: "ta_who_12", card: "傷心のギタリストが", part: 1},
  { voice: "ta_who_13", card: "通りすがりの忍者が", part: 1},
  { voice: "ne_who_7", card: "有名プロゲーマーが", part: 1},
  { voice: "ne_who_8", card: "筋肉自慢のボディービルダーが", part: 1},
  { voice: "ne_who_9", card: "サンタクロースが", part: 1},
  { voice: "ne_who_10", card: "有名配信者が", part: 1},
  { voice: "ne_who_11", card: "迷子のエルフが", part: 1},
  { voice: "ne_who_12", card: "徹夜明けのエンジニアが", part: 1},
  { voice: "ne_who_13", card: "生意気な小学生が", part: 1},
  { voice: "ka_whe_7", card: "放課後の教室で", part: 2},
  { voice: "ka_whe_8", card: "シングルベッドの上で", part: 2},
  { voice: "ka_whe_9", card: "煮えたぎる鍋の中で", part: 2},
  { voice: "ka_whe_10", card: "巨大なスプーンの上で", part: 2},
  { voice: "ka_whe_11", card: "タワマンの最上階で", part: 2},
  { voice: "ka_whe_12", card: "授業中の教室で", part: 2},
  { voice: "ka_whe_13", card: "男子更衣室の真ん中で", part: 2},
  { voice: "ta_whe_7", card: "霧が深い墓地で", part: 2},
  { voice: "ta_whe_8", card: "冷蔵庫の野菜室の中で", part: 2},
  { voice: "ta_whe_9", card: "銀行の巨大金庫の前で", part: 2},
  { voice: "ta_whe_10", card: "世紀末の荒野で", part: 2},
  { voice: "ta_whe_11", card: "深夜のファミレスで", part: 2},
  { voice: "ta_whe_12", card: "滝が流れる修行場で", part: 2},
  { voice: "ta_whe_13", card: "宇宙ステーションの窓際で", part: 2},
  { voice: "ne_whe_7", card: "地下格闘技場のリングで", part: 2},
  { voice: "ne_whe_8", card: "大行列のラーメン屋の先頭で", part: 2},
  { voice: "ne_whe_9", card: "緊迫した裁判所の法廷で", part: 2},
  { voice: "ne_whe_10", card: "熱いローソクを垂らされながら", part: 2},
  { voice: "ne_whe_11", card: "誰もいない深夜の公園で", part: 2},
  { voice: "ne_whe_12", card: "ピラミッドの頂上で", part: 2},
  { voice: "ne_whe_13", card: "一週間かえてないパンツの中で", part: 2},
  { voice: "ka_why_1", card: "世界平和のために", part: 3},
  { voice: "ka_why_2", card: "ギャルと2人きりで", part: 3},
  { voice: "ka_why_3", card: "徹夜明けのテンションで", part: 3},
  { voice: "ka_why_4", card: "生配信のネタ作りのために", part: 3},
  { voice: "ka_why_5", card: "親の仕送りに感謝しながら", part: 3},
  { voice: "ka_why_6", card: "己の煩悩を消し去るために", part: 3},
  { voice: "ka_why_7", card: "罰ゲームのスクワットをしながら", part: 3},
  { voice: "ka_why_8", card: "推しのライブに当選した勢いで", part: 3},
  { voice: "ka_why_9", card: "面接に遅刻しそうになって", part: 3},
  { voice: "ka_why_10", card: "給料日前の切なさに耐えかねて", part: 3},
  { voice: "ka_why_11", card: "一世一代の大博打に勝って", part: 3},
  { voice: "ka_why_12", card: "宿題を家に忘れた言い訳として", part: 3},
  { voice: "ka_why_13", card: "宇宙の真理に辿り着いた結果", part: 3},
  { voice: "ta_why_1", card: "上司の愚痴をぶちまけながら", part: 3},
  { voice: "ta_why_2", card: "運命のダイスを振るために", part: 3},
  { voice: "ta_why_3", card: "誰もが二度見するドヤ顔で", part: 3},
  { voice: "ta_why_4", card: "昔の黒歴史を思い出して", part: 3},
  { voice: "ta_why_5", card: "幼馴染との約束を守るために", part: 3},
  { voice: "ta_why_6", card: "支払いのギガ数が足りなくなって", part: 3},
  { voice: "ta_why_7", card: "異世界転生に失敗したせいで", part: 3},
  { voice: "ta_why_8", card: "会社の偉い人と気まずい沈黙の中で", part: 3},
  { voice: "ta_why_9", card: "生配信の視聴者10万人に見守られながら", part: 3},
  { voice: "ta_why_10", card: "悪の組織のボスと肩を組みながら", part: 3},
  { voice: "ta_why_11", card: "オカンから着信が来ている画面を見つめながら", part: 3},
  { voice: "ta_why_12", card: "明日の支払いのギガ数が足りなくなって", part: 3},
  { voice: "ta_why_13", card: "初恋の相手にそっくりなアンドロイドの前で", part: 3},
  { voice: "ne_why_1", card: "前世の記憶が突然フラッシュバックしたせいで", part: 3},
  { voice: "ne_why_2", card: "自分の全財産を賭けた大勝負の直前に", part: 3},
  { voice: "ne_why_3", card: "クラスの気になるあの子と目が合った瞬間に", part: 3},
  { voice: "ne_why_4", card: "誰も自分の言葉を信じてくれないので", part: 3},
  { voice: "ne_why_5", card: "推しの限定グッズが1秒で売り切れたショックで", part: 3},
  { voice: "ne_why_6", card: "お腹が信じられないくらいピーピー鳴り響く中で", part: 3},
  { voice: "ne_why_7", card: "英語しか通じない謎の集団に囲まれながら", part: 3},
  { voice: "ne_why_8", card: "近所の野良猫とメンチを切り合いながら", part: 3},
  { voice: "ne_why_9", card: "占い師に「今日があなたのターニングポイント」と言われて", part: 3},
  { voice: "ne_why_10", card: "涙目でわさびのツーンとする痛みに耐えながら", part: 3},
  { voice: "ne_why_11", card: "出前が2時間遅れて発狂した勢いで", part: 3},
  { voice: "ne_why_12", card: "重力が通常の3倍になったかのような錯覚の中で", part: 3},
  { voice: "ne_why_13", card: "幼い頃に生き別れた双子の兄と奇跡の再会を果たして", part: 3},
  { voice: "ka_wha_7", card: "悔しさのあまり気絶した", part: 4},
  { voice: "ka_wha_8", card: "お尻にタトゥーを入れた", part: 4},
  { voice: "ka_wha_9", card: "よからぬ想像をした", part: 4},
  { voice: "ka_wha_10", card: "アイデンティティの危機を感じた", part: 4},
  { voice: "ka_wha_11", card: "耳から血を出した", part: 4},
  { voice: "ka_wha_12", card: "無心で修行に打ち込んだ", part: 4},
  { voice: "ka_wha_13", card: "激しい恋に落ちた", part: 4},
  { voice: "ta_wha_7", card: "華麗なバク転を決めた", part: 4},
  { voice: "ta_wha_8", card: "必死で命乞いをした", part: 4},
  { voice: "ta_wha_9", card: "領収書をシュレッダーにかけた", part: 4},
  { voice: "ta_wha_10", card: "歓喜の阿波踊りを踊った", part: 4},
  { voice: "ta_wha_11", card: "マカロンを一口で飲み込んだ", part: 4},
  { voice: "ta_wha_12", card: "激辛カレーを完食した", part: 4},
  { voice: "ta_wha_13", card: "盛大にずっこけた", part: 4},
  { voice: "ne_wha_7", card: "ぬるぬるのウナギを掴んだ", part: 4},
  { voice: "ne_wha_8", card: "突然ポエムを詠み始めた", part: 4},
  { voice: "ne_wha_9", card: "激しくうろたえた", part: 4},
  { voice: "ne_wha_10", card: "泥酔してくだを巻いた", part: 4},
  { voice: "ne_wha_11", card: "奇跡のイリュージョンを披露した", part: 4},
  { voice: "ne_wha_12", card: "枕を涙で濡らした", part: 4},
  { voice: "ne_wha_13", card: "全財産でよくわからない株を買った", part: 4},
  { voice: "so_who_1", card: "初めて街に出た殿様が", part: 1},
  { voice: "so_who_2", card: "チャンネル登録者1億人の配信者が", part: 1},
  { voice: "so_who_3", card: "三度の飯より筋トレが好きなおばあちゃんが", part: 1},
  { voice: "so_who_4", card: "自我を持ったポンコツ洗濯機が", part: 1},
  { voice: "so_who_5", card: "徹夜明けで限界を迎えたおじいさんが", part: 1},
  { voice: "so_who_6", card: "犬に変装したエイリアンが", part: 1},
  { voice: "so_who_7", card: "初めてのおつかいに挑むちびっこが", part: 1},
  { voice: "so_who_8", card: "語尾に必ず『ロボ』とつける社長が", part: 1},
  { voice: "so_who_9", card: "明日のテストを諦めた女子高生が", part: 1},
  { voice: "so_who_10", card: "武器職人のおじいさんが", part: 1},
  { voice: "so_who_11", card: "自分を人間だと思い込んでいる野良猫が", part: 1},
  { voice: "so_who_12", card: "目立ちたがりのナルシストが", part: 1},
  { voice: "so_who_13", card: "お気に入りの傘を盗まれた幼稚園児が", part: 1},
  { voice: "so_whe_1", card: "お忍びで訪れた温泉旅館で", part: 2},
  { voice: "so_whe_2", card: "美術館の片隅で", part: 2},
  { voice: "so_whe_3", card: "プロレスのリング上で", part: 2},
  { voice: "so_whe_4", card: "スーパーのセルフレジの前で", part: 2},
  { voice: "so_whe_5", card: "ゲリラ豪雨の中で", part: 2},
  { voice: "so_whe_6", card: "怪しい薬が並ぶ実験室で", part: 2},
  { voice: "so_whe_7", card: "お祭りの屋台が並ぶ神社の境内で", part: 2},
  { voice: "so_whe_8", card: "ひまわりが咲き誇る畑で", part: 2},
  { voice: "so_whe_9", card: "真夜中の静まり返った水族館で", part: 2},
  { voice: "so_whe_10", card: "ビルの建設現場で", part: 2},
  { voice: "so_whe_11", card: "誰もいない遊園地の観覧車で", part: 2},
  { voice: "so_whe_12", card: "あの人の膝枕で", part: 2},
  { voice: "so_whe_13", card: "歴史的な条約が交わされる調印式で", part: 2},
  { voice: "so_why_1", card: "給料3ヶ月分もする壺を割ってしまって", part: 3},
  { voice: "so_why_2", card: "世界滅亡の10秒前に", part: 3},
  { voice: "so_why_3", card: "プロポーズを断られたショックで", part: 3},
  { voice: "so_why_4", card: "サボテンが突然喋り始めたことに驚いて", part: 3},
  { voice: "so_why_5", card: "ネットに投稿したポエムが炎上していると知って", part: 3},
  { voice: "so_why_6", card: "恐る恐る振り返った瞬間に", part: 3},
  { voice: "so_why_7", card: "スマホの広告だらけのゲームに熱中して", part: 3},
  { voice: "so_why_8", card: "ブラック企業から逃げ出しながら", part: 3},
  { voice: "so_why_9", card: "推しの結婚に理性を失って", part: 3},
  { voice: "so_why_10", card: "公衆トイレの紙がないことに気づいて", part: 3},
  { voice: "so_why_11", card: "曲がり角でぶつかったあの人と体が入れ替わって", part: 3},
  { voice: "so_why_12", card: "三歳児に「お前が次の選ばれし者だ」と囁かれて", part: 3},
  { voice: "so_why_13", card: "メイクがきまらないことにキレて", part: 3},
  { voice: "so_wha_1", card: "ディズニーランドに一人で行った", part: 4},
  { voice: "so_wha_2", card: "おしゃれな服屋で挙動不審になった", part: 4},
  { voice: "so_wha_3", card: "誰もが二度見する独創的なポーズを決めた", part: 4},
  { voice: "so_wha_4", card: "昔の黒歴史を思い出して激しくうろたえた", part: 4},
  { voice: "so_wha_5", card: "泥酔して周囲にひたすらくだを巻いた", part: 4},
  { voice: "so_wha_6", card: "推しのグッズを自作した", part: 4},
  { voice: "so_wha_7", card: "悔し涙を流しながら枕を濡らした", part: 4},
  { voice: "so_wha_8", card: "奇妙な踊りを踊った", part: 4},
  { voice: "so_wha_9", card: "最新のゲーム機を開封した", part: 4},
  { voice: "so_wha_10", card: "自分のアクリルスタンドを大量生産した", part: 4},
  { voice: "so_wha_11", card: "貯金をFXで溶かした", part: 4},
  { voice: "so_wha_12", card: "お気に入りのぬいぐるみを優しく抱きしめた", part: 4},
  { voice: "so_wha_13", card: "おやつを分け合って仲良く食べた", part: 4},
  { voice: "ka_who_14", card: "凄腕のSPが", part: 1},
  { voice: "ka_who_15", card: "号泣しているオタクが", part: 1},
  { voice: "ka_who_16", card: "マッドサイエンティストが", part: 1},
  { voice: "ka_who_17", card: "バイトに遅刻しそうな学生が", part: 1},
  { voice: "ka_who_18", card: "現代の原宿にタイムスリップした紫式部が", part: 1},
  { voice: "ka_who_19", card: "ムキムキの上腕二頭筋が", part: 1},
  { voice: "ka_who_20", card: "嘘をつけない呪いをかけられた政治家が", part: 1},
  { voice: "ta_who_14", card: "初来日でコンビニのおにぎりを食べたセレブが", part: 1},
  { voice: "ta_who_15", card: "親切なゾンビが", part: 1},
  { voice: "ta_who_16", card: "地声が低すぎる配信者が", part: 1},
  { voice: "ta_who_17", card: "経歴詐称で社長まで登りつめた男が", part: 1},
  { voice: "ta_who_18", card: "半額シールに命をかける女が", part: 1},
  { voice: "ta_who_19", card: "自分がゲームの登場人物と悟ったキャラが", part: 1},
  { voice: "ta_who_20", card: "人間に化けたタヌキが", part: 1},
  { voice: "ne_who_14", card: "大事な商談の日に二度寝をきめた男が", part: 1},
  { voice: "ne_who_15", card: "前髪が決まらなくて半日悩んだナルシストが", part: 1},
  { voice: "ne_who_16", card: "二郎系ラーメンのコールに緊張する客が", part: 1},
  { voice: "ne_who_17", card: "教科書の偉人に落書きしていた学生が", part: 1},
  { voice: "ne_who_18", card: "猫カフェの猫たちに無視されていた客が", part: 1},
  { voice: "ne_who_19", card: "赤ちゃん言葉でしゃべるおじさんが", part: 1},
  { voice: "ne_who_20", card: "宇宙から生配信をする宇宙飛行士が", part: 1},
  { voice: "so_who_14", card: "冬眠から目覚めた熊が", part: 1},
  { voice: "so_who_15", card: "手段を選ばぬ重課金兵が", part: 1},
  { voice: "so_who_16", card: "ツボに入ってしまった葬儀屋が", part: 1},
  { voice: "so_who_17", card: "硬派なタイトルをつけるラノベ作家が", part: 1},
  { voice: "so_who_18", card: "美容室でシャンプーに緊張する客が", part: 1},
  { voice: "so_who_19", card: "ご主人の帰宅を喜んだ犬が", part: 1},
  { voice: "so_who_20", card: "九九の七の段が怪しい男が", part: 1},
  { voice: "ka_whe_14", card: "真夏のコミケの行列で", part: 2},
  { voice: "ka_whe_15", card: "高級フレンチの席で", part: 2},
  { voice: "ka_whe_16", card: "システィーナ礼拝堂の中で", part: 2},
  { voice: "ka_whe_17", card: "怪しい光を放つピラミッドの奥で", part: 2},
  { voice: "ka_whe_18", card: "放課後の教室で", part: 2},
  { voice: "ka_whe_19", card: "実家のこたつで", part: 2},
  { voice: "ka_whe_20", card: "デパ地下の惣菜売り場で", part: 2},
  { voice: "ta_whe_14", card: "幽霊も逃げ出すような廃墟で", part: 2},
  { voice: "ta_whe_15", card: "将棋タイトル戦の対局場で", part: 2},
  { voice: "ta_whe_16", card: "CIAの作戦指令室で", part: 2},
  { voice: "ta_whe_17", card: "真剣勝負の碁盤の前で", part: 2},
  { voice: "ta_whe_18", card: "マングローブのジャングルで", part: 2},
  { voice: "ta_whe_19", card: "深夜の夜行バスの車内で", part: 2},
  { voice: "ta_whe_20", card: "冒険者が集う酒場の片隅で", part: 2},
  { voice: "ne_whe_14", card: "最新の洗浄便座の上で", part: 2},
  { voice: "ne_whe_15", card: "戦場と化したバーゲンセールの会場で", part: 2},
  { voice: "ne_whe_16", card: "恐竜の化石が見下ろす夜の博物館で", part: 2},
  { voice: "ne_whe_17", card: "不思議なトリックアートの部屋で", part: 2},
  { voice: "ne_whe_18", card: "無音の防音室の中で", part: 2},
  { voice: "ne_whe_19", card: "６つに割れた腹筋の上で", part: 2},
  { voice: "ne_whe_20", card: "おまわりさんの前で", part: 2},
  { voice: "so_whe_14", card: "盛り上がる神輿の上で", part: 2},
  { voice: "so_whe_15", card: "盗んだパンツをかぶりながら", part: 2},
  { voice: "so_whe_16", card: "誰もいない夕暮れの校庭で", part: 2},
  { voice: "so_whe_17", card: "煙と匂いが充満する焼き肉屋で", part: 2},
  { voice: "so_whe_18", card: "伝説の剣が刺さった岩の前で", part: 2},
  { voice: "so_whe_19", card: "ついに掘り当てた宝箱の前で", part: 2},
  { voice: "so_whe_20", card: "悲鳴が上がる拷問室の中で", part: 2},
  { voice: "ka_why_14", card: "オーディションの審査員の前で", part: 3},
  { voice: "ka_why_15", card: "タイムカプセルに入れた黒歴史ノートを読まれて", part: 3},
  { voice: "ka_why_16", card: "動物園の猿に笑われた腹いせに", part: 3},
  { voice: "ka_why_17", card: "スマホの画面が割れて", part: 3},
  { voice: "ka_why_18", card: "金髪美女と身振りで会話しながら", part: 3},
  { voice: "ka_why_19", card: "自分のドッペルゲンガーと鉢合わせしたせいで", part: 3},
  { voice: "ka_why_20", card: "腹いせにお菓子を食べ過ぎたせいで", part: 3},
  { voice: "ta_why_14", card: "ちいかわのぬいぐるみを抱きしめつつ", part: 3},
  { voice: "ta_why_15", card: "愛車が走行距離10万キロを突破した記念に", part: 3},
  { voice: "ta_why_16", card: "自分を勇者だと思い込む近所のおじさんと", part: 3},
  { voice: "ta_why_17", card: "幻のタピオカミルクティーを一口飲んだ勢いで", part: 3},
  { voice: "ta_why_18", card: "へそくりが家族に見つかって", part: 3},
  { voice: "ta_why_19", card: "突然、鼻がふくらんできたので", part: 3},
  { voice: "ta_why_20", card: "ラジオで自分のメールが読まれたので", part: 3},
  { voice: "ne_why_14", card: "絶対に怒らない温厚な上司を怒らせてしまい", part: 3},
  { voice: "ne_why_15", card: "あの人と運命の出会いを感じて", part: 3},
  { voice: "ne_why_16", card: "前世は王国の王子だと言い張って", part: 3},
  { voice: "ne_why_17", card: "カラオケの採点に納得がいかなくて", part: 3},
  { voice: "ne_why_18", card: "仕事が手につかなくなった結果", part: 3},
  { voice: "ne_why_19", card: "寝癖を親切なギャルに指摘されて", part: 3},
  { voice: "ne_why_20", card: "自作の銃を自慢しながら", part: 3},
  { voice: "so_why_14", card: "「明日から本気を出す」と今日も言い張って", part: 3},
  { voice: "so_why_15", card: "シークレットシューズをはいて", part: 3},
  { voice: "so_why_16", card: "白いTシャツにカレーの汁を飛ばされた悲しみを乗り越えて", part: 3},
  { voice: "so_why_17", card: "大富豪から「全財産を譲る」という手紙が届いて", part: 3},
  { voice: "so_why_18", card: "突如、アイドルグループのセンターになって", part: 3},
  { voice: "so_why_19", card: "無理やりデスゲームに参加させられて", part: 3},
  { voice: "so_why_20", card: "部屋の植物に毎朝クラシックを聴かせた結果", part: 3},
  { voice: "ka_wha_14", card: "渾身の変顔を全力で披露した", part: 4},
  { voice: "ka_wha_15", card: "和牛を網の上で焦がした", part: 4},
  { voice: "ka_wha_16", card: "自撮り棒を限界まで伸ばして撮影した", part: 4},
  { voice: "ka_wha_17", card: "引きこもって動画サイトを見続けた", part: 4},
  { voice: "ka_wha_18", card: "ハトのモノマネを完コピした", part: 4},
  { voice: "ka_wha_19", card: "床に落ちたポテチを3秒ルールで食べた", part: 4},
  { voice: "ka_wha_20", card: "狂ったようにヒヨコの雄と雌をわけた", part: 4},
  { voice: "ta_wha_14", card: "見事なステップで人々を踏みつけた", part: 4},
  { voice: "ta_wha_15", card: "寿命がちぢまった", part: 4},
  { voice: "ta_wha_16", card: "華やかなポーズを決めながら気絶した", part: 4},
  { voice: "ta_wha_17", card: "値引きシールの貼られた惣菜を独り占めした", part: 4},
  { voice: "ta_wha_18", card: "お気に入りのマグカップを粉砕した", part: 4},
  { voice: "ta_wha_19", card: "怒りのあまり切腹した", part: 4},
  { voice: "ta_wha_20", card: "前髪のセットを1ミリ単位で調整した", part: 4},
  { voice: "ne_wha_14", card: "ロボットダンスの動きで謝罪した", part: 4},
  { voice: "ne_wha_15", card: "契約書を破り捨てた", part: 4},
  { voice: "ne_wha_16", card: "芸能人のSNSにクソリプをつけた", part: 4},
  { voice: "ne_wha_17", card: "自分の靴下が左右逆であることに気づいた", part: 4},
  { voice: "ne_wha_18", card: "気まずい空気を変えるために口笛を吹いた", part: 4},
  { voice: "ne_wha_19", card: "誰も聞いていない武勇伝を熱く語った", part: 4},
  { voice: "ne_wha_20", card: "誹謗中傷をして逮捕された", part: 4},
  { voice: "so_wha_14", card: "家がカニの臭いでいっぱいになった", part: 4},
  { voice: "so_wha_15", card: "記憶をなくした", part: 4},
  { voice: "so_wha_16", card: "限界まで息を止めて顔を真っ赤にした", part: 4},
  { voice: "so_wha_17", card: "警官の機嫌が悪かったので逮捕された", part: 4},
  { voice: "so_wha_18", card: "駅のホームでシャドーボクシングをやり出した", part: 4},
  { voice: "so_wha_19", card: "モテなさすぎて死んだ", part: 4},
  { voice: "so_wha_20", card: "鏡に向かって「お前は誰だ」と問いかけた", part: 4},

];

export const BASE_VOICE_URL = "assets/voice/";
